import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import {Toaster} from "@/components/ui/sonner";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const _inter = Inter({ subsets: ["latin", "vietnamese"] });
const _jetbrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`antialiased`}
      >
        <Toaster position={'bottom-right'} />
        {children}
      </body>
    </html>
  );
}
