worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log off;
    error_log  /dev/stderr warn;

    # Define the "upstream" server
    upstream nextjs_upstream {
        server frontend:3000;
    }

    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://nextjs_upstream;

            # These headers pass the user's real IP address and info through Nginx to Next.js
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Cache Next.js static assets
        location /_next/static/ {
            proxy_pass http://nextjs_upstream;
            proxy_cache_valid 60m;
            expires 1y;
            access_log off;
        }
    }
}