apiVersion: v1
kind: Secret
metadata:
  name: gw-secrets
  namespace: guardianway
type: Opaque
stringData:
  POSTGRES_USER: gw
  POSTGRES_PASSWORD: gw_pw
  POSTGRES_DB: guardianway
  DATABASE_URL: postgresql://gw:gw_pw@postgres:5432/guardianway
  DIRECT_URL: postgresql://gw:gw_pw@postgres:5432/guardianway
  REDIS_URL: redis://redis:6379
  JWT_ACCESS_SECRET: ci-demo-access-secret
  JWT_REFRESH_SECRET: ci-demo-refresh-secret
  WEB_BASE_URL: http://frontend:3000
  EMAIL_USERNAME: info.guardianway@gmail.com
  EMAIL_PASSWORD: goxunfxtnxmghdfr